name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: 🧪 Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            ln -s ../ ./node_modules/wdio-safaridriver-service
            ls -la ./node_modules
            npm test

